# Generated by Django 6.0.3 on 2026-03-03 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('players_per_match', models.PositiveSmallIntegerField()),
                ('rounds_per_match', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('a', 'Active'), ('p', 'Pending'), ('e', 'Ended')], default='p', max_length=1)),
                ('decks_per_user', models.PositiveSmallIntegerField(default=1)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('match_qty', models.PositiveIntegerField(default=0)),
                ('points_win', models.PositiveIntegerField(default=5)),
                ('points_loss', models.PositiveIntegerField(default=0)),
                ('points_draw', models.PositiveIntegerField(default=1)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league_tracker.format')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='League_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_player_points', models.IntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_tracker.league')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('league_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='league_tracker.league_player')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('p', 'Pending'), ('c', 'Completed')], default='p', max_length=1)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_tracker.league')),
            ],
        ),
        migrations.CreateModel(
            name='Match_Player_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league_tracker.deck')),
                ('league_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league_tracker.league_player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='league_tracker.match')),
            ],
        ),
        migrations.CreateModel(
            name='Match_Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('c', 'Completed'), ('p', 'Pending')], default='p', max_length=1)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='league_tracker.match')),
            ],
        ),
        migrations.CreateModel(
            name='Match_Round_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('w', 'Win'), ('d', 'Draw'), ('l', 'Loss')], default='d', max_length=1)),
                ('points', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='league_tracker.match_player_detail')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='league_tracker.match_round')),
            ],
        ),
        migrations.AddConstraint(
            model_name='league_player',
            constraint=models.UniqueConstraint(fields=('league', 'player'), name='uq_league_player'),
        ),
        migrations.AddConstraint(
            model_name='deck',
            constraint=models.UniqueConstraint(fields=('league_player', 'name'), name='uq_deck_per_league_player_name'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('league', 'number'), name='uq_match_number_per_league'),
        ),
        migrations.AddConstraint(
            model_name='match_player_detail',
            constraint=models.UniqueConstraint(fields=('match', 'league_player'), name='uq_match_league_player'),
        ),
        migrations.AddConstraint(
            model_name='match_round',
            constraint=models.UniqueConstraint(fields=('match', 'number'), name='uq_round_number_per_match'),
        ),
        migrations.AddConstraint(
            model_name='match_round_player',
            constraint=models.UniqueConstraint(fields=('round', 'player'), name='uq_round_player_once'),
        ),
    ]
